### ISSUE TITLE
Como administrador do WordPress, quero instalar o plug-in Agenda de Eventos da BVS

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/bvs-events-calendar#30]
Seguir as boas práticas do WP para criação do plug-in responsável pelo funcionamento da Agenda de Eventos da BVS.

**Comment by wilsonmoura** [comment]
- [ ] Criar estrutura de arquivos padronizada para plugin

**Comment by wilsonmoura** [comment]
User Story concluída no [Sprint Maio 1](https://github.com/bireme/bvs-events-calendar/issues?q=milestone%3A%22Sprint+Maio+1%22)
