### ISSUE TITLE
Replicar caixa de diálogo de publicar no final do formulário de cada custom post type

### ISSUE THREAD

**Issue by marcoslmori** [bireme/bvs-events-calendar#41]
Para seguir o fluxo natural do preenchimento dos formulários, principalmente na edição, que ocorrerá frequentemente devido ao fluxo de associação dos participantes com as subsessões e apresentações, seria uma melhoria importante ter a caixa de diálogo de publicar no final do formulário

![image](https://cloud.githubusercontent.com/assets/10047460/15686925/acacaf7c-2748-11e6-9aad-fa7d7f60b452.png)

**Comment by wilsonmoura** [comment]
Esse é um comportamento padrão do WordPress que não será alterado no plugin.
Documentar no guia rápido que são para usuários familiarizados com a interface do WordPress.
Colocar o link do manual do WordPress no guia rápido.

**Comment by marcoslmori** [comment]
Quando documentado no guia de uso o issue será fechado.

**Comment by marcoslmori** [comment]
Criado issue especifico para documetação
