### ISSUE TITLE
Colocar os horários das apresentações na página pública

### ISSUE THREAD

**Issue by marcoslmori** [bireme/bvs-events-calendar#42]
Um cenário muito comum nos congressos é você montar uma agenda pessoal porque  ocorrem muitos eventos ao mesmo tempo.  Sem a informação do horário que irá ocorrer o evento fica difícil organizar essa agenda  

![image](https://cloud.githubusercontent.com/assets/10047460/15687406/e2fa1388-274a-11e6-84d3-f6941c5e556c.png)

**Comment by wilsonmoura** [comment]
@marcoslmori 

Os campo de data inicial e final foram adicionados nas apresentações.

Favor validar.

**Comment by marcoslmori** [comment]
Ok fiz o teste e está tudo certo. Exemplo: http://mti.teste.bireme.org/agenda-eventos/schedule/programa/
