### ISSUE TITLE
Na associação das apresentações com  as sessões/subsessões devem ser identificado por titulo e data (ou outro separador).

### ISSUE THREAD

**Issue by marcoslmori** [bireme/bvs-events-calendar#44]
Isso ocorre também na associação de subsessão com sessão

No exemplo, mostra o termo "Conferencia 2 vezes". Sendo que não me identifica em que data são essas sessões para que eu possa associar de forma correta sem deduzir qual é a  correta

![image](https://cloud.githubusercontent.com/assets/10047460/15688330/e090b336-274f-11e6-939b-638fdc48ffc1.png)

**Comment by wilsonmoura** [comment]
Avalias os seguintes cenários:
- Eliminar a função de entrada de eventos e assumir a instalação do plugin em subsite, sendo a página inicial o próprio programa.
- Filtrar o campo de relacionamento por evento.
- Incluir título do evento e data inicial no título dos campos relacionados.

**Comment by wilsonmoura** [comment]
Resolvido em 103fbbbd4762198f3f62d1020ac34aafdd471b91 e 5947500a49c2cf047f08e385c91bddc17c050dde

**Comment by wilsonmoura** [comment]
@marcoslmori 

Foram adicionadas as informações do título do evento e data inicial das sessões/subsessões.

Favor validar.

**Comment by marcoslmori** [comment]
Validada o item acima referido, no entanto, vamos ter um problema de identificação na edição quando existir sessão ou subsessão com nomes iguais.  É necessario manter o mesmo formato de associação da subsessão com a sessão 

![image](https://cloud.githubusercontent.com/assets/10047460/17909578/754bd0bc-695b-11e6-84a8-9decd035ccec.png)

**Comment by wilsonmoura** [comment]
@marcoslmori 

Para administrar as colunas na lista dos post types, deve-se instalar o plugin [Admin Columns](https://br.wordpress.org/plugins/codepress-admin-columns/).

**Comment by marcoslmori** [comment]
Foi instalado, no entanto é necessário configurar a coluna para cada CPTs adicionando complexidade na configuração do plugin.  Se viesse já configurado por padrão seria o adequado

**Comment by renatomurasaki** [comment]
@wilsonmoura a regra de visualização das colunas é:

- No CPT SubSession, mostrar coluna Sessão
- No CPT Presentations, mostrar colunas Sessão e Subsessão

**Comment by wilsonmoura** [comment]
@marcoslmori 

Realizamos os ajustes para que as colunas solicitadas sejam exibidas sem a necessidade de instalação de plugins específicos.

Favor validar.

**Comment by wilsonmoura** [comment]
Issue encerrado por inatividade. Vamos reabrir essa atividade caso necessário.
