### ISSUE TITLE
Na página pública do programa do evento, na seção do Slider, colocar as horas de inicio e fim da sessão/subsessão ou apresentações

### ISSUE THREAD

**Issue by marcoslmori** [bireme/bvs-events-calendar#45]
Informação importante para o usuário programar a participação

![image](https://cloud.githubusercontent.com/assets/10047460/15688738/dcea98a8-2751-11e6-8b3d-aec645f60971.png)

**Comment by wilsonmoura** [comment]
@pierrima poderia sugerir um layout que contemple a apresentação do horário final de cada sessão que aparece no slider? Atualmente, só é exibida a data inicial.

**Comment by pierrima** [comment]
Realizado
