### ISSUE TITLE
No custom post type de participante tem que ter o campo de função (role) para identificar o papel nas apresentações ou subsessão/sessão

### ISSUE THREAD

**Issue by marcoslmori** [bireme/bvs-events-calendar#46]
Esse campo de deve ser mostrado no site público. 

![image](https://cloud.githubusercontent.com/assets/10047460/15688937/fa29221c-2752-11e6-877d-ab28001dcd5c.png)

**Comment by marcoslmori** [comment]
Caso o participante tenha mais de uma função,  será necessário cadastrar mais de uma vez o participante?

**Comment by marcoslmori** [comment]
Esse chamado foi reaberto  por que não existe o campo de role para ingressar dados.  Mesmo assim, para cada papel que o participante tiver será preciso cadastrar novamente

**Comment by renatomurasaki** [comment]
@wilsonmoura Avaliar o workaround de criação de um campo de texto com o seguinte comportamento: cada linha conterá o papel;slug da sessão ou subsessão ou apresentação. Dessa maneira é possível associar mais de um role para o mesmo participante. A solução de tradução tb está resolvida, considerando que o plug-in polylang gera uma versão do mesmo CPT por idioma.

**Comment by wilsonmoura** [comment]
@marcoslmori 

O campo Role foi adicionado aos participantes conforme descrição desse chamado.

Favor validar.

**Comment by marcoslmori** [comment]
Para relacionamento dos participantes com os seus respectivos CPT e seu papel funcionou corretamente. 

Uma melhoria que seria mais eficiente no fluxo de relacionamento do participante com o CPTs seria mostrar os participantes em ordem alfabética #71  

Referente para adicionar um novo participante, esse não aparece no site público. issue #70

**Comment by renatomurasaki** [comment]
Melhorias serão atendidas nos issues #70 e #71.
