### ISSUE TITLE
Criar um shortcut para "Adicionar participantes" nos customs posts types de apresentação, sessão e subsessão com refresh automático

### ISSUE THREAD

**Issue by marcoslmori** [bireme/bvs-events-calendar#47]
Com esse shortcut possibilita que o usuário cadastre os cpt sem necessidade de quebrar o fluxo para cadastrar o participante para associar na sessão, subsessão e apresentação.

**Comment by wilsonmoura** [comment]
No fluxo padrão para criação de apresentação, sessão e subsessão, deve-se antes criar os participantes, para que possa associá-los em cada custom post type mencionado. @marcoslmori isso deve ficar claro no guia rápido.

**Comment by marcoslmori** [comment]
issue para documentação já criada em #66
