### ISSUE TITLE
Por padrão o plugin agenda de eventos não deve ter publicado nenhum widget na área do logo

### ISSUE THREAD

**Issue by marcoslmori** [bireme/bvs-events-calendar#48]
Atualmente na ativação do tema "bvs events calendar", estão vindo publicados na area do logo os seguintes widgets: pesquisar, tópicos recentes, comentários, arquivos, categoria e meta. Esses widgets publicados impacta no layout da página pública.

![image](https://cloud.githubusercontent.com/assets/10047460/15689733/c8ffbd5a-2756-11e6-8a7d-c835c7c9ef40.png)

**Comment by wilsonmoura** [comment]
Esse é um comportamento padrão do WordPress, que assume alguns widgets quando se trata de um site/subsite novo. @marcoslmori favor documentar.

**Comment by marcoslmori** [comment]
criado issue #68 para essa documentação
