### ISSUE TITLE
O campo de descrição dos CPTs sessão e subsessão não está sendo publicado no formato detalhado.

### ISSUE THREAD

**Issue by marcoslmori** [bireme/bvs-events-calendar#49]
![image](https://cloud.githubusercontent.com/assets/10047460/15689961/a5cb4268-2757-11e6-8fc3-0577e8753afe.png)

**Comment by wilsonmoura** [comment]
@marcoslmori 

O campo de descrição das sessões/subsessões foi implementado na visualização pública.

Favor validar.

**Comment by marcoslmori** [comment]
decisão tomada no issue 56
O campo de descrição será removido do formulário de entrada dos custom post types Sessão e Subsessão. Isso será substituído pelo campo de resumo (excerpt). O local de exibição desse campo será apresentado após o dado de participantes, clicando no ícone Detalhes.

**Comment by marcoslmori** [comment]
Validado em sessão Sessão, subsessão e apresentações
