### ISSUE TITLE
Criar um filtro por eventos para todos os CPTs

### ISSUE THREAD

**Issue by marcoslmori** [bireme/bvs-events-calendar#51]
![image](https://cloud.githubusercontent.com/assets/10047460/15723614/a333500a-2819-11e6-85a7-b8dc12d7aa47.png)

Essa implementação serve para fazer a gestão dos CPTs de acordo com os eventos.

**Comment by wilsonmoura** [comment]
Essa ação está pendente da avaliação de permanência do custom post type `event`. Essa avaliação também é exigida no issue #44

**Comment by wilsonmoura** [comment]
Enviar o ID do evento selecionado no filtro para o formulário do respectivo custom post type.

**Comment by wilsonmoura** [comment]
@marcoslmori 

O filtro foi implementado conforme descrição.

Favor validar.

**Comment by marcoslmori** [comment]
Para programas, sessões, subsessões, apresentações apresentam os filtros com os títulos dos eventos.  No CPT participantes, aparecem todos participantes de todos os eventos cadastrados. Documentar que a melhor forma de escolher os participantes quando tiver muitos participantes é melhor fazer a pesquisa

**Comment by renatomurasaki** [comment]
Fechado issue pois a documentação será tratada no #73
