### ISSUE TITLE
Por padrão não é possível criar um subsite por evento porque a AI foi projetada para listar os eventos

### ISSUE THREAD

**Issue by marcoslmori** [bireme/bvs-events-calendar#52]
![image](https://cloud.githubusercontent.com/assets/10047460/15723733/3fae5510-281a-11e6-945b-78f07907886d.png)

Talvez seja necessário criar documentação para customizar com o page builder

**Comment by wilsonmoura** [comment]
Se a avaliação de permanência do custom post type `event`, sendo realizada nos issues #44 e #51, for aprovada, desenvolver condição que, ao identificar somente um evento, mostra a homepage do evento.

**Comment by wilsonmoura** [comment]
O comportamento da homepage está documentada na issue #61

**Comment by wilsonmoura** [comment]
Ajustar breadcrumb nos casos que houverem somente um evento/programa registrado.

**Comment by wilsonmoura** [comment]
Breadcrumb ajustado conforme consta na issue #62

**Comment by wilsonmoura** [comment]
@marcoslmori 

A condição de exibição da homepage foi implementada de acordo com a descrição.

Favor validar.

**Comment by marcoslmori** [comment]
Validado em localhost e funciona de acordo com o que foi solicitado 

![image](https://cloud.githubusercontent.com/assets/10047460/18177980/e354631e-7052-11e6-8e8a-5c8af098d656.png)
