### ISSUE TITLE
Ao adicionar os  CPTs do plugin da agenda de eventos estão apresentando as categorias de todos os eventos do subsite

### ISSUE THREAD

**Issue by marcoslmori** [bireme/bvs-events-calendar#53]
O Ideal é que mostre apenas as categorias especificas do evento 

![image](https://cloud.githubusercontent.com/assets/10047460/15724007/81817cd2-281b-11e6-9ef8-d84986d8f290.png)

**Comment by wilsonmoura** [comment]
Se a avaliação de permanência do custom post type event, sendo realizada nos issues #44 e #51, for aprovada, somente serão mostradas as categorias relativas àquele evento.

**Comment by renatomurasaki** [comment]
@marcoslmori  O comportamento padrão do WP é associar a taxonomia category para um site ou subsite, quando usada a versão multisite. O plug-in Agenda de Eventos se comporta como um serviço de agendas, possibilitando criar várias agendas dentro de um mesmo site. Dessa maneira, todos as agendas compartilharão a mesma taxonomia category.

**Comment by renatomurasaki** [comment]
@wilsonmoura Antes de encerrarmos este chamado como "won´t fix", por favor, verificar a possibilidade de customizar o metadado da categoria, associando um campo adicional a cada valor para informar o evento associado. Talvez possa gerar um hook na listagem da categoria para mostrar somente os valores associados ao evento.

**Comment by wilsonmoura** [comment]
@marcoslmori 

O dado Evento foi adicionado nas categorias.

Favor validar.

**Comment by marcoslmori** [comment]
Com essa solução irá existir uma etapa a mais para cada processo de cadastramento de um CPT, além de retirar a funcionalidade de ingressar categorias dentro de cada contexto. 

Avaliar a possibilidade de poder ingressar categoria dentro do CPTs do contexto do evento,

Pensando em minimizar a clareza do processo, penso que deveria cadastrar as categorias apenas em eventos, retirando esse item dos outros CPTs. 

![image](https://cloud.githubusercontent.com/assets/10047460/18180511/8c40c9e0-705d-11e6-99cf-8b226048f3fc.png)

Um outro problema é não poder relacionar a categoria para mais de um evento, forçando, caso haja categorias iguais para eventos diferentes, duplicar o processo de escolher cadastramento. 

![image](https://cloud.githubusercontent.com/assets/10047460/18180608/031f67b0-705e-11e6-91be-585b426fe93e.png)

**Comment by wilsonmoura** [comment]
@marcoslmori 

Resolvido em 3b4a0c820e49a9fc169bdf399b8b1fb58c0d396c

Favor atualizar o plugin e validar.

**Comment by marcoslmori** [comment]
documentar que nos participantes aparecem todos as categorias de todos os eventos

**Comment by marcoslmori** [comment]
Pelos testes que eu fiz, tudo funcionou  corretamente

![image](https://cloud.githubusercontent.com/assets/10047460/18249987/91531e04-7357-11e6-8b88-e1c5e829c6fc.png)

**Comment by wilsonmoura** [comment]
@marcoslmori 

Resolvido em da85be4010438c18260b00bdf71337a23b42c10f.

Favor validar.

**Comment by wilsonmoura** [comment]
Mostrar a lista de categorias apenas no CPT Presentation.
