### ISSUE TITLE
Formato detalhado da página pública de apresentação  não exibe a descrição e o resumo mesmo não tendo conteúdo exibe o rótulo

### ISSUE THREAD

**Issue by marcoslmori** [bireme/bvs-events-calendar#54]
![image](https://cloud.githubusercontent.com/assets/10047460/15724285/c87fe258-281c-11e6-9739-ec16556264cf.png)

**Comment by wilsonmoura** [comment]
O campo de resumo será removido do formulário de entrada. Isso será substituído pelo campo de descrição (content).
