### ISSUE TITLE
No site público, nas  sessões e subsessões não exibem os campos de "Descrição" e "Resumo" 

### ISSUE THREAD

**Issue by marcoslmori** [bireme/bvs-events-calendar#56]
![image](https://cloud.githubusercontent.com/assets/10047460/15725377/f32cfc16-2821-11e6-9902-e679c231de7f.png)

**Comment by wilsonmoura** [comment]
O campo de descrição será removido do formulário de entrada dos custom post types Sessão e Subsessão. Isso será substituído pelo campo de resumo (excerpt). O local de exibição desse campo será apresentado após o dado de participantes, clicando no ícone **Detalhes**.

**Comment by wilsonmoura** [comment]
Esse comportamento está contemplado na avaliação do issue #49

**Comment by wilsonmoura** [comment]
@marcoslmori 

Retiramos o campo de descrição do formulário das sessões e subsessões. Além disso, ajustamos a interface pública para mostrar o resumo dos mesmos.

Favor validar.

**Comment by marcoslmori** [comment]
Validado em sessão Sessão, subsessão e apresentações
