### ISSUE TITLE
Em apresentações deve poder subir mais de um arquivo 

### ISSUE THREAD

**Issue by marcoslmori** [bireme/bvs-events-calendar#57]
No CPTs de apresentações só pode subir um arquivo. Sendo que em conferencias ou algum outro tipo de apresentação, é necessário ter a possibilidade de subir mais de um arquivo

![image](https://cloud.githubusercontent.com/assets/10047460/15782603/60e387ec-2981-11e6-9506-ba174a291ad2.png)

**Comment by wilsonmoura** [comment]
O comportamento do plugin é associar uma apresentação para um participante. Nas exceções em que ocorrem mais de um participante para a mesma participação, dividir a apresentação em partes e associá-las para cada participante. @marcoslmori favor documentar no guia rápido.

**Comment by marcoslmori** [comment]
> Dividir a apresentação em partes e associá-las para cada participante. @marcoslmori favor documentar no guia rápido.
É uma solução artificial que não representa a granulidade da apresentação e portanto não documentar. Acho melhor deixar no backlog e definir como limitação do sistema.

**Comment by renatomurasaki** [comment]
Se uma apresentação tiver 2 participantes com 2 arquivos independentes, recomenda-se a criação de duas apresentações independentes associadas a uma sessão ou subsessão.

Caso seja apenas um arquivo, apresentado por duas pessoas, criar apenas uma apresentação com 2 participantes.

@marcoslmori favor documentar.

**Comment by wilsonmoura** [comment]
Issue encerrado por inatividade. Vamos reabrir essa atividade caso necessário.
