### ISSUE TITLE
Em participantes, existem no formulário campo descrição e resumo e não está sendo mostrado na página pública detalhada

### ISSUE THREAD

**Issue by marcoslmori** [bireme/bvs-events-calendar#58]
![image](https://cloud.githubusercontent.com/assets/10047460/15782807/0389d366-2982-11e6-9c64-871d4335415b.png)

**Comment by wilsonmoura** [comment]
Esse comportamento está contemplado na avaliação do issue #49

**Comment by wilsonmoura** [comment]
Esse comportamento está contemplado na avaliação do issue #49
