### ISSUE TITLE
Revisar a regra de mostrar na página pública somente o campo de descrição ou de resumo 

### ISSUE THREAD

**Issue by marcoslmori** [bireme/bvs-events-calendar#59]
Isso ocorre em todos os CPTs.

Os campos de descrição e resumo não tem o mesmo tipo de conteúdo. Em descrição pode ter informações diferentes ao do resumo.  Por essa razão, a regra deveria ser de mostrar os campos desde que estejam preenchidos e não, mesmo que tenham sido preenchidos os dois campos, mostrar apenas a descrição 

![image](https://cloud.githubusercontent.com/assets/10047460/15783237/c6216dca-2983-11e6-887a-6f5339efff9b.png)

**Comment by wilsonmoura** [comment]
Esse comportamento está contemplado na avaliação do issue #58
