### ISSUE TITLE
Problema de ordenação  cronológica das apresentações 

### ISSUE THREAD

**Issue by marcoslmori** [bireme/bvs-events-calendar#64]
![image](https://cloud.githubusercontent.com/assets/10047460/17597705/7e5500f8-5fcd-11e6-8b20-22ec30586ac3.png)

**Comment by renatomurasaki** [comment]
Tornar o campo de data obrigatório e ordenar por data e hora inicial.

**Comment by wilsonmoura** [comment]
@marcoslmori 

Ajustamos as apresentações para serem exibidas em ordem cronológica.

Favor validar.

**Comment by marcoslmori** [comment]
Funcionando corretamente

![image](https://cloud.githubusercontent.com/assets/10047460/18250833/edd01746-735b-11e6-9226-1f89999f50e9.png)

**Comment by renatomurasaki** [comment]
Funcionando corretamente.
