### ISSUE TITLE
Documentar  a recomendação cadastrar os participantes antes de cadastrar os cpt respectivos 

### ISSUE THREAD

**Issue by marcoslmori** [bireme/bvs-events-calendar#66]
Documentar  recomendação cadastrar os participantes antes de cadastrar os cpt respectivos (sessão, subsessão e etc)

Referente ao issue #43

**Comment by marcoslmori** [comment]
recomendação do chamado #47
"No fluxo padrão para criação de apresentação, sessão e subsessão, deve-se antes criar os participantes, para que possa associá-los em cada custom post type mencionado. @marcoslmori isso deve ficar claro no guia rápido."

**Comment by wilsonmoura** [comment]
Issue encerrado por inatividade. Vamos reabrir essa atividade caso necessário.
