### ISSUE TITLE
Documentar que a melhor forma de escolher os participantes quando tiver muitos participantes é fazer a pesquisa

### ISSUE THREAD

**Issue by marcoslmori** [bireme/bvs-events-calendar#73]
Para programas, sessões, subsessões, apresentações apresentam os filtros com os títulos dos eventos. No CPT participantes, aparecem todos participantes de todos os eventos cadastrados. Documentar que a melhor forma de escolher os participantes quando tiver muitos participantes é fazer a pesquisa

Origem da demanda #51

**Comment by wilsonmoura** [comment]
Issue encerrado por inatividade. Vamos reabrir essa atividade caso necessário.
