### ISSUE TITLE
Documentar na wiki

### ISSUE THREAD

**Issue by marcoslmori** [bireme/bvs-events-calendar#85]

**Comment by marcoslmori** [comment]
Configuração do wp-config - Chamado do CRICS10
Instalação do plugin Font Awesome: https://br.wordpress.org/plugins/better-font-awesome/
Documentar como plugin homologado: https://br.wordpress.org/plugins/wordpress-importer/

**Comment by wilsonmoura** [comment]
Issue encerrado por inatividade. Vamos reabrir essa atividade caso necessário.
