### ISSUE TITLE
Fazer layout da página do participante

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/bvs-events-calendar#90]
Exemplo - http://crics10.org/eventos/participant/marcos-luis-mori/

**Comment by wilsonmoura** [comment]
@renatomurasaki nesse exemplo, a página de participante está montada, faltando somente a foto do participante. Tem mais alguma sugestão de visualização dessa página?

**Comment by renatomurasaki** [comment]
@wilsonmoura vejo que a caixa contendo os links das redes sociais agora aparece corretamente alinhado com os dados do participante. Creio que a caixa poderia ter uma cor neutra por padrão (cinza) e somente aparecer quando há informação a mostrar.
