### ISSUE TITLE
Retirar/avaliar o menu com os títulos do programa 

### ISSUE THREAD

**Issue by marcoslmori** [bireme/bvs-events-calendar#97]
![image](https://user-images.githubusercontent.com/10047460/44229185-9ea63500-a16d-11e8-9975-1a15ab78a854.png)

No entanto quando o evento tem vários dias é necessário navegar por esses dias

**Comment by wilsonmoura** [comment]
Sugestão: no slider, exibir o nome programa e âncoras para os dias do evento (ver imagem).

![slider](https://user-images.githubusercontent.com/3779520/44585227-efc3b380-a781-11e8-82fa-3ae4ea225f4b.png)

**Comment by renatomurasaki** [comment]
Me parece boa a ideia. Qual seria o comportamento quando o evento tem apenas um dia? Sairia o slider? Favor consultar equipe da Verônica.

**Comment by wilsonmoura** [comment]
@renatomurasaki quando o evento tem apenas um dia, vai aparecer somente o nome do programa no slider.

@marcoslmori favor entrar em contato com a equipe da Verônica para validar a sugestão proposta.
